### PR TITLE
customizing sign in and sign up pages, also added metadata for title …

### PR DESCRIPTION
**Pull request by Ali-Herrera**
…changes on different pages

### CODE REVIEW

**Review by victoriamcn — APPROVED** [review]

**Review by Ali-Herrera — COMMENTED** [review]
Merging into main

**Review by victoriamcn — APPROVED** [review]
this is my review!

**Review by victoriamcn — APPROVED** [review]
everything looks good!

**Review by victoriamcn — DISMISSED** [review]

**Review by victoriamcn — APPROVED** [review]
approved !!

**Pull request merged**
